- name: Remove old VMs
  hosts: proxmox
  tasks:
    - name: Stop VMs
      command: "{{ item }}"
      loop: 
        - qm stop 1000
        - qm stop 1100
        - qm stop 1200
      ignore_errors: true

    - name: Destroy (and Purge) VMs
      command: "{{ item }}"
      loop: 
        - qm destroy 1000 -purge
        - qm destroy 1100 -purge
        - qm destroy 1200 -purge
      ignore_errors: true