- name: Setup Proxmox
  hosts: proxmox
  tasks:
    - name: Ensure ability to update (with no subscription)
      block:
        - name: Add no-subscription source
          lineinfile:
            path: /etc/apt/sources.list
            line: "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"

        - name: Read pve-enterprise source
          shell: cat /etc/apt/sources.list.d/pve-enterprise.list
          register: file_contents
          changed_when: false

        - name: Ensure pve-enterprise line doesnt exist
          replace:
            path: /etc/apt/sources.list.d/pve-enterprise.list
            regexp: "deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
            replace: ""
          when: "'deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise' in file_contents.stdout"

      rescue:
        - name: Handle errors
          debug:
            msg: "An error occurred while processing the file."
    
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - curl
          - build-essential
          - libguestfs-tools
          - python3-dev
          - python3-pip

    - name: Install necessary pip libraries
      pip:
        name: 
          - virtualenv
          - proxmoxer
          - requests
        state: present 

    - name: Create cloud-init Directory
      file:
        path: /root/cloud-init
        state: directory

    - name: Create SSH key file
      copy:
        content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwuK8oXohD/woyzodo7kFc7w220VnGi99MvRRmPR4Rqp+FiyomhVfIXzBYWkI8rCR7YK/XV69l5+Zf6toLk5GimBMnZwXkAygWGHJw4PWNPS9cL+6a7bd1uoL9EMTfn/OR9kSCKcXfU4IlzNmKYOyrzZZNAX7btAzHEN23rtQ18HBJuakn7+TsqziGZywLCmRPL8dZNsSqYQ39zMnCGN13gqU+qZassKe/AIGRt1C+qksB7ltVEtDnZwBY8u1Nh3eR6XSi7N/Tw7RHXY+vNSK4rMlaamskNujf7WibjVCvSxB30RGelHEUPEmDl6tB2BD3CtPqnDemk653nHNvHgVscCCyBYcRe2W0FQ26Y4ZNUiL5w0UQBvgKs4p1eIF2axEgI85ZhcrUwg7wCo7JgEa6UyJsOA49/xgj71e5gnkf39pbWjWgy0PmW7Kb/SmYzaKaKuUYOsiqkob0a6SRKZqQfrecinUpRKOgJ7unn59bEp7+Zkm2uAdMj5spKGCUfMU= ansible@raspberrypi"
        dest: /root/cloud-init/ansible_key.pub
