- import_playbook: setup_proxmox.yaml
- import_playbook: setup_image.yaml

- import_playbook: create_docker.yaml
- import_playbook: create_wordpress.yaml

- import_playbook: setup_docker.yaml
- import_playbook: setup_wordpress.yaml

- import_playbook: update_self.yaml