- name: Setup Proxmox
  hosts: proxmox
  tasks:
    - name: Ensure ability to update (with no subscription)
      block:
        - name: Add no-subscription source
          lineinfile:
            path: /etc/apt/sources.list
            line: "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"

        - name: Read pve-enterprise source
          shell: cat /etc/apt/sources.list.d/pve-enterprise.list
          register: file_contents
          changed_when: false

        - name: Ensure pve-enterprise line doesnt exist
          replace:
            path: /etc/apt/sources.list.d/pve-enterprise.list
            regexp: "deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
            replace: ""
          when: "'deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise' in file_contents.stdout"

      rescue:
        - name: Handle errors
          debug:
            msg: "An error occurred while processing adding proxmox no-subscription source."
    
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - curl
          - build-essential
          - libguestfs-tools
          - python3-dev
          - python3-pip

    - name: Install necessary pip libraries
      pip:
        name: 
          - virtualenv
          - proxmoxer
          - requests
        state: present 