- name: Establish connection
  hosts: wordpress
  gather_facts: no
  tasks:
    - name: Disable host key checking
      set_fact:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      run_once: true

    - name: Wait for connection
      wait_for_connection:

    - name: Wait for cloud init to finish
      cloud_init_data_facts:
        filter: status
      register: cloud_init_result
      until: "cloud_init_result.cloud_init_data_facts.status.v1.stage is defined and not cloud_init_result.cloud_init_data_facts.status.v1.stage"
      retries: 20
      delay: 15

    - name: Gather Facts
      setup:

    - name: Enable host key checking
      set_fact:
        ansible_ssh_common_args: ""
      run_once: true

- name: Setup WordPress
  hosts: wordpress
  vars_files:
  - env.yml
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install extra packages
      apt:
        name:
          - apache2
          - ghostscript
          - libapache2-mod-php
          - mariadb-server
          - python3-pip
          - php
          - php-bcmath
          - php-curl
          - php-imagick
          - php-intl
          - php-json
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
        state: present  

    - name: Install pip libraries
      pip:
        name: 
          - pymysql

    - name: Install and Configure WordPress
      block:
        - name: Create WordPress Directory
          file:
            path: /srv/www
            state: directory
            owner: www-data
            group: www-data

        - name: Download WordPress
          get_url:
            url: "https://wordpress.org/latest.tar.gz"
            dest: "/tmp/wordpress.tar.gz"
            mode: '0644'

        - name: Extract WordPress
          unarchive:
            src: "/tmp/wordpress.tar.gz"
            dest: "/srv/www"
            remote_src: yes
            owner: www-data
            group: www-data
          become: true

        - name: Create sites-available Directory
          file:
            path: /etc/apache2/sites-available
            state: directory

        - name: Create wordpress.conf File
          file:
            path: /etc/apache2/sites-available/wordpress.conf
            state: touch

        - name: Configure Apache
          lineinfile:
            path: /etc/apache2/sites-available/wordpress.conf
            line: |
              <VirtualHost *:80>
                  DocumentRoot /srv/www/wordpress
                  <Directory /srv/www/wordpress>
                      Options FollowSymLinks
                      AllowOverride Limit Options FileInfo
                      DirectoryIndex index.php
                      Require all granted
                  </Directory>
                  <Directory /srv/www/wordpress/wp-content>
                      Options FollowSymLinks
                      Require all granted
                  </Directory>
              </VirtualHost>
            insertafter: EOF

        - name: Enable Apache site and modules
          command: "a2ensite wordpress"

        - name: Enable Apache Rewrite Module
          command: "a2enmod rewrite"

        - name: Disable default Apache site
          command: "a2dissite 000-default"

        - name: Reload Apache
          service:
            name: apache2
            state: reloaded

    - name: Configure Database for WordPress
      block:
        - name: Start MySQL service
          service:
            name: mysql
            state: started

        - name: Wait for MySQL to start
          wait_for:
            host: localhost
            port: 3306
            state: started

        - name: Create MySQL database (command)
          command: mysql -u root -e 'CREATE DATABASE IF NOT EXISTS wordpress;'

        - name: Create MySQL user (command)
          command: mysql -u root -e 'CREATE USER IF NOT EXISTS wordpress@localhost IDENTIFIED BY "WP-admin123";'

        - name: Grant MySQL user (command)
          command: mysql -u root -e 'GRANT ALL ON wordpress.* TO wordpress@localhost;'

        # # This doesnt wanna work

        # - name: Create MySQL database for WordPress
        #   mysql_db:
        #     name: wordpress

        # - name: Create MySQL user for WordPress
        #   mysql_user:
        #     name: wordpress
        #     password: 'WP-admin123'
        #     priv: 'wordpress.*:ALL'
        #     host: 'localhost'

        - name: Restart MySQL service
          service:
            name: mysql
            state: restarted

    - name: Configure WordPress
      block:
        - name: Copy WordPress config file
          command: "cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php"

        - name: Update WordPress config
          replace:
            path: /srv/www/wordpress/wp-config.php
            regexp: "{{ item.regexp }}"
            replace: "{{ item.replace }}"
          loop:
            - { regexp: 'database_name_here', replace: 'wordpress' }
            - { regexp: 'username_here', replace: 'wordpress' }
            - { regexp: 'password_here', replace: 'WP-admin123' }

        - name: Update WordPress salts
          replace:
            path: /srv/www/wordpress/wp-config.php
            regexp: "{{ item.regexp }}"
            replace: "{{ item.replace }}"
          loop:
            - { regexp: 'put your unique phrase here', replace: 'serverdemo' }

    - name: Restart Apache
      service:
        name: apache2
        state: restarted