# - name: Establish connection
#   hosts: wordpress
#   gather_facts: no
#   tasks:
#     - name: Disable host key checking
#       set_fact:
#         ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
#       run_once: true

#     - name: Wait for connection
#       wait_for_connection:

#     - name: Wait for cloud init to finish
#       cloud_init_data_facts:
#         filter: status
#       register: cloud_init_result
#       until: "cloud_init_result.cloud_init_data_facts.status.v1.stage is defined and not cloud_init_result.cloud_init_data_facts.status.v1.stage"
#       retries: 20
#       delay: 15

#     - name: Gather Facts
#       setup:

#     - name: Enable host key checking
#       set_fact:
#         ansible_ssh_common_args: ""
#       run_once: true

- name: Setup WordPress
  hosts: wordpress
  vars_files:
  - env.yml
  become: yes
  tasks:
    # - name: Update APT cache
    #   apt:
    #     update_cache: yes

    # - name: Install extra packages
    #   apt:
    #     name:
    #       - apache2
    #       - ghostscript
    #       - libapache2-mod-php
    #       - default-mysql-server
    #       - python3-pip
    #       - php
    #       - php-bcmath
    #       - php-curl
    #       - php-imagick
    #       - php-intl
    #       - php-json
    #       - php-mbstring
    #       - php-mysql
    #       - php-xml
    #       - php-zip
    #     state: present  

    # - name: Install pymysql
    #   pip:
    #     name: pymysql

    # - name: Install and Configure WordPress
    #   block:
    #     - name: Create WordPress Directory
    #       file:
    #         path: /srv/www
    #         state: directory
    #         owner: www-data
    #         group: www-data

    #     - name: Download WordPress
    #       get_url:
    #         url: "https://wordpress.org/latest.tar.gz"
    #         dest: "/tmp/wordpress.tar.gz"
    #         mode: '0644'

    #     - name: Extract WordPress
    #       unarchive:
    #         src: "/tmp/wordpress.tar.gz"
    #         dest: "/srv/www"
    #         remote_src: yes
    #         owner: www-data
    #         group: www-data
    #       become: true

    #     - name: Create sites-available Directory
    #       file:
    #         path: /etc/apache2/sites-available
    #         state: directory

    #     - name: Create wordpress.conf File
    #       file:
    #         path: /etc/apache2/sites-available/wordpress.conf
    #         state: touch

    #     - name: Configure Apache
    #       lineinfile:
    #         path: /etc/apache2/sites-available/wordpress.conf
    #         line: |
    #           <VirtualHost *:80>
    #               DocumentRoot /srv/www/wordpress
    #               <Directory /srv/www/wordpress>
    #                   Options FollowSymLinks
    #                   AllowOverride Limit Options FileInfo
    #                   DirectoryIndex index.php
    #                   Require all granted
    #               </Directory>
    #               <Directory /srv/www/wordpress/wp-content>
    #                   Options FollowSymLinks
    #                   Require all granted
    #               </Directory>
    #           </VirtualHost>
    #         insertafter: EOF

    #     - name: Enable Apache site and modules
    #       command: "a2ensite wordpress"

    #     - name: Enable Apache Rewrite Module
    #       command: "a2enmod rewrite"

    #     - name: Disable default Apache site
    #       command: "a2dissite 000-default"

    #     - name: Reload Apache
    #       service:
    #         name: apache2
    #         state: reloaded

    - name: Configure Database for WordPress
      block:
        - name: Start MySQL service
          ansible.builtin.service:
            name: mysql
            state: started
          become_user: root
          become: true

        - name: Wait for MySQL to start
          ansible.builtin.wait_for:
            host: localhost
            port: 3306
            state: started
          become_user: root
          become: true

        - name: Create MySQL database for WordPress
          ansible.builtin.mysql_db:
            name: wordpress
          become_user: root
          become: true

        - name: Create MySQL user for WordPress
          ansible.builtin.mysql_user:
            name: wordpress
            password: 'WP-admin123'
            priv: 'wordpress.*:ALL'
            host: 'localhost'
          become_user: root
          become: true

    - name: Configure WordPress
      block:
        - name: Copy WordPress config file
          command: "cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php"
          become_user: www-data

        - name: Update WordPress config
          replace:
            path: /srv/www/wordpress/wp-config.php
            regexp: "{{ item.regexp }}"
            replace: "{{ item.replace }}"
          become_user: www-data
          loop:
            - { regexp: 'database_name_here', replace: 'wordpress' }
            - { regexp: 'username_here', replace: 'wordpress' }
            - { regexp: 'password_here', replace: 'WP-admin123' }

        - name: Update WordPress salts
          replace:
            path: /srv/www/wordpress/wp-config.php
            regexp: "{{ item.regexp }}"
            replace: "{{ item.replace }}"
          become_user: www-data
          loop:
            - { regexp: 'put your unique phrase here', replace: 'serverdemo' }

    - name: Restart Apache
      service:
        name: apache2
        state: restarted




# // wordpress install

# sudo mkdir -p /srv/www
# sudo chown www-data: /srv/www
# curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www


# // Config apache

# // Create file:
# /etc/apache2/sites-available/wordpress.conf

# // Dit moet erin:
# <VirtualHost *:80>
#     DocumentRoot /srv/www/wordpress
#     <Directory /srv/www/wordpress>
#         Options FollowSymLinks
#         AllowOverride Limit Options FileInfo
#         DirectoryIndex index.php
#         Require all granted
#     </Directory>
#     <Directory /srv/www/wordpress/wp-content>
#         Options FollowSymLinks
#         Require all granted
#     </Directory>
# </VirtualHost>
# //


# sudo a2ensite wordpress

# sudo a2enmod rewrite

# sudo a2dissite 000-default

# sudo service apache2 reload 


# // Config database

# sudo mysql -u root

# CREATE DATABASE wordpress;

# CREATE USER wordpress@localhost IDENTIFIED BY 'WP-admin123'

# GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
#     -> ON wordpress.*
#     -> TO wordpress@localhost;

# GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
#     -> ON wordpress.*
#     -> TO wordpress@localhost;

# quit

# sudo service mysql start


# // wordpress config

# sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
# sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
# sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
# sudo -u www-data sed -i 's/password_here/WP-admin123/' /srv/www/wordpress/wp-config.php




# /srv/www/wordpress/wp-config.php

# DIT IS DE FILE : 

# define('AUTH_KEY',		    'put your unique phrase here');
# define('SECURE_AUTH_KEY',	'put your unique phrase here');
# define('LOGGED_IN_KEY',		'put your unique phrase here');
# define('NONCE_KEY',		    'put your unique phrase here');
# define('AUTH_SALT',		    'put your unique phrase here');
# define('SECURE_AUTH_SALT',	'put your unique phrase here');
# define('LOGGED_IN_SALT',	'put your unique phrase here');
# define('NONCE_SALT',		'put your unique phrase here');

# dit moet er worden veranderd: 

# define( 'AUTH_KEY',         'serverdemo' );
# define( 'SECURE_AUTH_KEY',  'serverdemo' );
# define( 'LOGGED_IN_KEY',    'serverdemo' );
# define( 'NONCE_KEY',        'serverdemo' );
# define( 'AUTH_SALT',        'serverdemo' );
# define( 'SECURE_AUTH_SALT', 'serverdemo' );
# define( 'LOGGED_IN_SALT',   'serverdemo' );
# define( 'NONCE_SALT',       'serverdemo' );

