- name: Setup Grafana Datasource and Dashboard
  hosts: monitor
  become: true
  tasks:    
    - name: Set up Grafana with CLI
      command: >
        grafana-cli admin reset-admin-password admin

    - name: Configure Grafana data source
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop: 
        - { regexp: "^;datasources = /etc/grafana/datasources", line: "datasources = /etc/grafana/datasources" }

    - name: Restart Grafana service
      systemd:
        name: grafana-server
        state: restarted

# # Returns not authorized so we do it using curl
    # - name: Add Prometheus as a data source
    #   uri:
    #     url: http://localhost:3000/api/datasources
    #     method: POST
    #     user: admin
    #     password: admin
    #     body_format: json
    #     body: '{"name": "Prometheus", "type": "prometheus", "url": "http://localhost:9090", "access": "proxy", "isDefault": true}'

    - name: Add Prometheus as a data source using curl
      command: > 
        curl -X POST -u admin:admin -H "Content-Type: application/json" -d '{"name": "Prometheus", "type": "prometheus", "url": "http://localhost:9090", "access": "proxy", "isDefault": true}' http://localhost:3000/api/datasources

# Original node-exporter-full.json from: https://github.com/rfmoz/grafana-dashboards 
    - name: Upload Prometheus Dashboard using curl
      command: >
        curl -X POST -u admin:admin -H "Content-Type: application/json" --data-binary @/home/ansible/ansible/import_dashboard.json http://localhost:3000/api/dashboards/import

    - name: Restart Grafana service again
      systemd:
        name: grafana-server
        state: restarted