- name: Establish connection
  hosts: docker
  gather_facts: no
  tasks:
    - name: Disable host key checking
      set_fact:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      run_once: true

    - name: Wait for connection
      wait_for_connection:

    - name: Wait for cloud init to finish
      cloud_init_data_facts:
        filter: status
      register: cloud_init_result
      until: "cloud_init_result.cloud_init_data_facts.status.v1.stage is defined and not cloud_init_result.cloud_init_data_facts.status.v1.stage"
      retries: 20
      delay: 15

    - name: Gather Facts
      setup:

    - name: Enable host key checking
      set_fact:
        ansible_ssh_common_args: ""
      run_once: true

- name: Setup Docker
  hosts: docker
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Add Docker and Python
      block:
        - name: Add docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
          register: docker_gpg_key

        - name: Create /etc/apt/keyrings directory
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Download and install Docker's GPG key
          shell: |
            curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            chmod a+r /etc/apt/keyrings/docker.gpg
          when: docker_gpg_key.changed

        - name: Add Docker repository to Apt sources
          lineinfile:
            path: /etc/apt/sources.list.d/docker.list
            line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable"
            create: yes

        - name: Update APT cache
          apt:
            update_cache: yes

        - name: Install extra packages (Python and Docker)
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present

        - name: Start the Docker service
          service:
            name: docker
            state: started

        - name: Download and install Docker Composer
          shell: |
            curl -SL "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
          when: docker_gpg_key.changed # Assume it only needs to be installed if docker needs to be installed